### ISSUE TITLE
一直stream opened

### ISSUE THREAD

**Issue by tfdetang** [sola97/docker-ss-kcp-udpspeeder#2]
使用示例的docker run 代码部署了服务端与客户端 (ss + kcptun + udp2raw)；
但是无法翻墙，在客户端的容器里看log，一直显示 stream opened (正常应该是 stream opened 和 stream closed 都有)；  请问下是怎么回事呢？

**Comment by sola97** [comment]
我写了个生成命令脚本放上去了，你可以试试
windows下的话虚拟机的nat和docker都是跑不通的

**Comment by tfdetang** [comment]
谢谢，我再来试试。 我不是在windows下跑的，客户端docker是跑在群晖里的。  我的系统组织方式是   服务端(ss+kcp+udp2raw) --> 群晖 (kcp + udp2raw) --> 梅林(ss + 透明代理)。 所以应该和 nat 没有关系吧

**Comment by tfdetang** [comment]
用了下脚本，依然是老问题。后来去服务端的容器也打了一下log看，才发现 出现failed to set TCP_FASTOPEN_CONNECT 的报错信息。搜了下 mritd/shadowsocks 的 issue里也有人遇到这个问题，似乎是一个内核版本的兼容问题(服务器用的centos, 内核是3.10的。

**Comment by sola97** [comment]
因为都是我自己在ubutnu用，所以那边修了，我这边还没修
我脚本里在服务端的写死了--fast-open，你可以去掉试试

**Comment by tfdetang** [comment]
谢谢 大佬，我已经去掉了 --fast-open，去掉就没问题了
