### ISSUE TITLE
请问下如何提高端口安全？

### ISSUE THREAD

**Issue by aetherwu** [sola97/docker-ss-kcp-udpspeeder#3]
我看到有只暴露最外层端口+密码的，而脚本里是全开放的（可能需要依赖防火墙来保护）。
能否有直接生成只暴露必要端口的方案？

**Comment by sola97** [comment]
看需求可以在脚本的docker命令部分去掉几行

服务端6443端口可以用SS客户端来直连，应对没有kcptun的环境，如果不考虑就可以去掉两个方案里的
-p {server_ss_port+server_num}:6443
-p {server_ss_port+server_num}:6443/udp

客户端的6500端口暴露出来可以在用来做国内中转服务器或者开放给局域网，给安卓的SS客户端之类的用
-p {client_ss_port+client_offset}:6500
-p {client_ss_port+client_offset}:6500/udp

1080端口自然就给启docker的服务器本机用的，对应脚本这两行
-p {client_socks5_port+client_offset}:1080
-p {client_socks5_port+client_offset}:1080/udp

个人认为都是用得到的一些端口

`

**Comment by aetherwu** [comment]
感谢指点。
还有一个问题，在 generate.py 输出时（我只修改了密码），我注意到服务端脚本输出：

```
    -t "-s -l0.0.0.0:4096 -r 127.0.0.1:6500   ...
    -T "-s -l0.0.0.0:4097 -r 127.0.0.1:6501   ...
```

我理解的是服务器开启了 4097/4097 两个 UDP 端口等待服务端来连接。

而同时客户端脚本输出：

```
    -t "-c -l0.0.0.0:3333  -rIP_ADDR:4098  ...
    -T "-c -l0.0.0.0:3334  -rIP_ADDR:4099  ...
```

看上去远程端口和服务端 Docker 命令启动的端口对不上。
我想问一下，这里是正确的脚本，还是说，这两组端口应该是对应关系？

谢谢，打扰了。

**Comment by aetherwu** [comment]
还有两个问题打扰：

1、在 **方案二-客户端-相当于执行** 里：

我看到 README显示 

```
udp2raw -c -l0.0.0.0:3333  -r$SS_SERVER_IP:4096 
udp2raw -c -l0.0.0.0:3333  -r$SS_SERVER_IP:4096 
``` 

不知道这是有意为之还是属于 typo？

2、 generate 脚本输出建议：

```
客户端本地映射SS端口：6501
SOCKS5端口：1081
```

能否求教一下，如果是 Surge 这样的客户端，具体应该指定 localhost 的哪个端口呢？（好像应该是 6501 ？相当于映射回本地的远程服务器 SSS 端口，是这样吗？

**Comment by sola97** [comment]
1、笔误，已更新README
2、理解的没错，可以参考这篇文章
[UDPspeeder + kcptun/finalspeed + $$ 同时加速tcp和udp流量](https://github.com/wangyu-/UDPspeeder/wiki/UDPspeeder---kcptun-finalspeed---$$-%E5%90%8C%E6%97%B6%E5%8A%A0%E9%80%9Ftcp%E5%92%8Cudp%E6%B5%81%E9%87%8F)

**Comment by aetherwu** [comment]
不论如何，在macOS上的部署还是失败了，测试连不通。
比较悲剧的是看log也比较茫然，不知道问题在哪。
感谢你的指点。
